env:
    - GO111MODULE=on
  
  before:
    hooks:
      - go mod download
  
  builds:
    - id: goecho
      binary: goecho
      ldflags: -s -w
      env:
        - CGO_ENABLED=0
      goos:
        - darwin
        - linux
        - windows
      goarch:
        - amd64
        - arm
        - arm64
      goarm:
        - 6
        - 7
      ignore:
        - goos: darwin
          goarch: 386
  
  archives:
    -
      replacements:
        darwin: Darwin
        linux: Linux
        windows: Windows
        386: i386
        amd64: x86_64
  
  release:
    github:
      owner: techrick
      name: goecho
    prerelease: auto
  
  checksum:
    name_template: "checksums.txt"
